artifact.sh

issue #31 related to travis build failing after resync with tidepool

---

app/pages/patient/patientteam.js

bug was created by merge with upstream 2fc8072076243c8b17b11e7ddfb82efdf2fc7bee
related to PR #34

Fix issue related to use of HIDE_UPLOAD_LINK

---

app/components/chart/weekly.js

See [PT-69](https://diabeloop.atlassian.net/browse/PT-69)

[PT-69] Fix User is automatically disconnected from blip

---

app/routes.js

See [PT-39](https://diabeloop.atlassian.net/browse/PT-39) and [PT-40](https://diabeloop.atlassian.net/browse/PT-40)

PT-40: Add a link to the daily view in Blip from parameters history timeline

---

app/core/api.js

See https://diabeloop.atlassian.net/browse/PT-17

PT-17 #done Save user profile may trigger a race condition with seagull.

---

app/pages/patientdata/patientdata.js

PT-163 Fix Unknown DOM property class. Did you mean className?

---

.npmrc
package.json
yarn.lock

- use viz.0.1.0 from local registry
- Travis job has to be configured with new `nexus_token` variable

PT-192 Upgrade viz to 0.1.0 (dblp version)

---

package.json
yarn.lock

a new tag has to be created for version 0.1.7 that will include MVP for branding

PT-171 update viz and tideline versions for blip 0.1.7

---

app/pages/signup/signup.js
app/pages/signup/signup.less
config.app.js
config.webpack.js
config/local.sh
package.json
webpack.config.js

See https://diabeloop.atlassian.net/browse/PT-227

PT-227 Disable the default create patient account page

---

.dockerignore
Dockerfile
package-lock.json

Use a more recent version of Viz
Fake nexus_token in the dockerfile to make npm install work OK.

fix docker build issue.

---

app/core/utils.js
app/pages/login/login.js
app/pages/login/login.less
app/pages/patients/patients.js
app/routes.js
locales/en/translation.json
locales/fr/translation.json
test/unit/routes.test.js

even it some restrictions are remaining for those browsers:
"Firefox 66, YourLoops a l'air de fonctionner pour l'affichage.
- Un petit bug pour la création des notes, il ne prend pas la bonne date
- des affichages un peu décalés (basale) mais rien de grave"
"Sur Edge même combat mais un peu moins bien
- bug idem pour la création des notes
- affichages décalés mais pas les memes décalages que FF (c'etait pas drole sinon)
- et l'écran tendance qui est difficilement lisible mais qui fonctionne

PT-365 Firefox, Chrome on iOS and edge are now enabled

---

CHANGELOG.md
app/routes.js
config/env.docker.sh
package-lock.json
package.json
test/unit/routes.test.js

Per configuration, we can prevent from patient signup. In that case, the "/signup/personal" page should not be accessible. Today this is possible.
Fix this minor glitch.
Note: the redirection described in routes.js do work only when the "remember me" checkbox is ticked when login to YourLoops

PT-532 One can create a patient even if the application is not allowing it

---

CHANGELOG.md
package.json

Bump version for YourLoops 1.6.0

Bump version to 0.11

---

CHANGELOG.md
app/pages/patientdata/patientdata.js

remove code which is not necessary in the PDF generation

PT-1128 Quick fix for auto switch when using refresh button

---

CHANGELOG.md
app/redux/actions/async.js
app/redux/constants/errorMessages.js
config.app.js
config.webpack.js
config/env.docker.sh
config/local.sh
locales/de/translation.json
locales/en/translation.json
locales/fr/translation.json
webpack.config.js

Dirty code... but doing a better message will need to make too much changes.

PT-1027 Inform the user when he has reach a max login attempt

---

CHANGELOG.md
app/core/utils.js
test/unit/utils/utils.test.js

PT-1157 Revert "PT-1115 SP8 patients are not displayed with correct time"

---

CHANGELOG.md
Dockerfile
app/core/language.js
app/pages/userprofile/userprofile.js
package.json

fixing regression from 7f2af74
ToDo: bump to 1.0.0

Fix regression introduced in 7f2af74

---

CHANGELOG.md
package.json

PT-1172: Display of parameter history in Device Settings page does not manage correctly the timezone information

PT-1172: update viz version to the latest

---

CHANGELOG.md
app/pages/userprofile/index.js
app/pages/userprofile/userprofile.js
test/unit/pages/userprofile.test.js

PT-1168 Fix display bug when updating user profile

---

.npmrc
CHANGELOG.md
locales/languages.json
package-lock.json
package.json

YLP-157 Add german locale

---

Jenkinsfile
ci.yml

Documentation (i.e. soup list) was not generated...

Engineering: add a doc generation step in the pipeline

---

CHANGELOG.md
app/components/loginnav/loginnav.js
app/config.js
app/core/api.js
app/pages/login/login.js
cloudfront-dist/deployment/docker.template.env
config/env.docker.sh
config/local.sh
package-lock.json
package.json
server/config.app.js
templates/matomo.js
test/unit/app/app.test.js
test/unit/app/core/api.test.js

Depends on https://github.com/mdblp/platform-client/pull/7
New configuration variable!
`METRICS_FORCED`

YLP-320 Matomo tracker is no longer active

---

CHANGELOG.md
locales/en/translation.json
locales/languages.json

documents will have to be updated accordingly: Terms of Use and Data Privacy

YLP-317 add switzerland

---

CHANGELOG.md
packages/blip/app/components/chart/daily.js
packages/tideline/css/tideline-colors.less
packages/tideline/css/tideline.less
packages/tideline/dev/testpage/types.js
packages/tideline/js/index.js
packages/tideline/js/plot/zenModeEvent.js
packages/tideline/js/tidelinedata.js
packages/tideline/js/validation/validate.js
packages/tideline/plugins/blip/chartdailyfactory.js
packages/tideline/test/tidelinedata_test.js

- add Zen mode and Confidential mode management in tideline data, deduplicate based on eventID and most recent inputTime
- display the zen mode event in the Glucose and Event section. 
- No tool tip
- Displayed in the background, all other events are on top of it.

YLP-236 Display zen mode

---

templates/zendesk.js

Correct shoreline external token route (post PR review)

---

packages/yourloops/app/app.tsx
packages/yourloops/components/header-bar.tsx
packages/yourloops/components/private-route.tsx
packages/yourloops/lib/auth/api.ts
packages/yourloops/lib/auth/hook/use-auth.tsx
packages/yourloops/models/shoreline.ts
packages/yourloops/pages/hcp/patient-data.tsx
packages/yourloops/pages/hcp/patients-list.tsx
packages/yourloops/pages/login/login.tsx
packages/yourloops/pages/patient/patient-data.tsx
packages/yourloops/pages/patient/patient.tsx
packages/yourloops/pages/request-passord-reset/index.ts
packages/yourloops/pages/request-passord-reset/request-password-reset.tsx

even if not all thing are  completed and perfect, i think we could merge it in order to share a base line as the auth provider fro exemple

YLP-433 Login page

---

package-lock.json
package.json
packages/yourloops/.eslintrc

Source: https://reactjs.org/docs/hooks-rules.html

Add eslint plugin for React hooks

---

CHANGELOG.md
packages/tideline/css/tideline.less
packages/tideline/js/plot/util/legend.js

YLP-423 Add Dexcom branding to the glucose graph

---

locales/de/yourloops.json
locales/en/yourloops.json
locales/es/yourloops.json
locales/fr/yourloops.json
locales/it/yourloops.json
locales/lol/yourloops.json
locales/nl/yourloops.json
packages/yourloops/pages/hcp/team-member-remove-dialog.tsx
packages/yourloops/pages/hcp/team-members-table.tsx

YLP-510 Display pending invitation members

---

packages/blip/app-patient-data/index.d.ts
packages/blip/app-patient-data/index.js
packages/blip/app-patient-data/patient-data.js
packages/blip/app/components/chart/footer.js
packages/blip/app/components/chart/trends.js
packages/blip/app/redux/utils/trackingMiddleware.js
packages/blip/test/unit/components/chart/footer.test.js
packages/yourloops/lib/auth/hook.tsx
packages/yourloops/types/globals.d.ts

* Cleanup few warnings
* Footer: use children
* Retore redux store state at logout only like v1

Fix some trends checkboxes actions

---

templates/index.html

@MarineDBL 
A message for IE users or older browsers

Intercept app load error on older browser

---

packages/yourloops/.eslintrc
packages/yourloops/lib/data/api.ts
packages/yourloops/lib/data/blip-api.ts
packages/yourloops/lib/team/hook.tsx
packages/yourloops/lib/team/models.ts
packages/yourloops/lib/utils.ts
packages/yourloops/models/device-data.ts
packages/yourloops/models/shoreline.ts
packages/yourloops/pages/hcp/patients-list-table.tsx
packages/yourloops/pages/hcp/patients-list.tsx

- Use tide-whisperer API v0 as a fallback (much slower)
- Fetch TIR informations only when a patient is displayed

YLP-367 Add fetch TIR

---

packages/yourloops/components/patient-data.tsx
packages/yourloops/components/primary-header-bar.tsx
packages/yourloops/components/routes.tsx
packages/yourloops/lib/auth/api.ts
packages/yourloops/lib/auth/hook.tsx
packages/yourloops/lib/data/api.ts
packages/yourloops/lib/team/api.ts
packages/yourloops/lib/team/hook.tsx
packages/yourloops/lib/utils.ts
packages/yourloops/models/generic.ts
packages/yourloops/models/shoreline.ts
packages/yourloops/pages/hcp/patients-list-table.tsx
packages/yourloops/pages/hcp/patients-list.tsx
packages/yourloops/pages/login/login.tsx
packages/yourloops/pages/notifications/notifications-list.tsx
packages/yourloops/pages/profile/profile.tsx
packages/yourloops/test/common/index.ts

** Do not squash this PR : It's 2 PR in one ! **
> When the HCP manually sort patients, sorting selection overrides flag
Was not implemented

YLP-372 Fix sort patient algorithm

---

packages/yourloops/components/icons/VerifiedIcon.tsx
packages/yourloops/components/primary-header-bar.tsx
packages/yourloops/components/team-card.tsx
packages/yourloops/pages/hcp/index.tsx
packages/yourloops/pages/hcp/patients-secondary-bar.tsx
packages/yourloops/pages/hcp/primary-nav-bar.tsx
packages/yourloops/pages/hcp/teams-page.tsx
packages/yourloops/pages/notifications/notification.tsx
packages/yourloops/pages/patient/caregivers.tsx
packages/yourloops/pages/patient/index.tsx
packages/yourloops/pages/patient/primary-nav-bar.tsx
packages/yourloops/pages/patient/teams.tsx
packages/yourloops/test/common/index.ts
packages/yourloops/test/pages/hcp/team-card.test.tsx
packages/yourloops/test/pages/hcp/teams-page.test.tsx
packages/yourloops/test/pages/notifications/notification.test.tsx

Two others PR will follow with the page content:
- YLP-612 => https://github.com/mdblp/blip/pull/450 
- YLP-613 => https://github.com/mdblp/blip/pull/451

YLP-554 Add patients shares pages

---

CHANGELOG.md

Bug fixed in PR #433
Just update the changelog for regulation.

YLP-266 Hour format isn't updated on daily view when language is changed

---

packages/yourloops/components/icons/PersonRemoveIcon.tsx
packages/yourloops/components/remove-patient-dialog.tsx
packages/yourloops/lib/share/api.ts
packages/yourloops/lib/share/reducer.tsx
packages/yourloops/pages/caregiver/index.tsx
packages/yourloops/pages/caregiver/patients/add-dialog.tsx
packages/yourloops/pages/caregiver/patients/page.tsx
packages/yourloops/pages/caregiver/patients/table.tsx
packages/yourloops/pages/caregiver/patients/types.ts
packages/yourloops/pages/hcp/team-edit-dialog.tsx
packages/yourloops/pages/hcp/team-members-table.tsx
packages/yourloops/pages/patient/caregivers/remove-dialog.tsx

* Add warning text in HCP add dialog too
* A fix for the snackbar will be added later

YLP-679 Caregivers: Add patient dialog

---

packages/yourloops/lib/team/api.ts
packages/yourloops/lib/team/hook.tsx
packages/yourloops/lib/team/models.ts
packages/yourloops/pages/caregiver/caregiver.tsx
packages/yourloops/pages/hcp/index.tsx
packages/yourloops/pages/hcp/patients/add-dialog.tsx
packages/yourloops/pages/hcp/patients/page.tsx
packages/yourloops/pages/hcp/patients/secondary-bar.tsx
packages/yourloops/pages/hcp/patients/table.tsx
packages/yourloops/pages/hcp/types.ts
packages/yourloops/pages/patient/caregivers/page.tsx
packages/yourloops/test/pages/hcp/patients-list-table.test.tsx
packages/yourloops/test/pages/hcp/patients-secondary-bar.test.tsx

* Rework invite patient dialog
* Display pending invitation only with the filter

YLP-498 HCP: Display pending invitation patients

---

packages/yourloops/pages/hcp/patients/page.tsx
packages/yourloops/pages/hcp/patients/team-code-dialog.tsx

The modale is displayed after an HCP invite a patient to
one of it's team.

YLP-685 Add HCP team code modal

---

packages/blip/app/components/patient-data.less
packages/tideline/css/tideline.less
packages/tideline/js/oneday.js
packages/tideline/js/plot/util/legend.js
packages/tideline/js/pool.js
packages/tideline/plugins/blip/chartdailyfactory.js

Question: Do I need to update the changelog ?
Please, squash me !

YLP-695 Fix legend overlap in daily bolus graph

---

packages/yourloops/lib/auth/hook.tsx
packages/yourloops/lib/language.ts
packages/yourloops/lib/zendesk.ts
templates/zendesk.js

Finally for v2.0 we will juste do the distinguish between login / logout.
Filter on articles / category etc. will be done in a next release.

YLP-697 Integrate zendesk

---

packages/blip/app/core/api-utils.js
packages/tideline/js/oneday.js
packages/tideline/js/plot/basal.js
packages/tideline/js/plot/confidentialModeEvent.js
packages/tideline/js/plot/deviceParameterChange.js
packages/tideline/js/plot/physicalActivity.js
packages/tideline/js/plot/reservoir.js
packages/tideline/js/plot/suspend.js
packages/tideline/js/plot/util/drawphysicalactivity.js
packages/tideline/js/plot/zenModeEvent.js
packages/tideline/js/pool.js
packages/tideline/js/tidelinedata.js
packages/tideline/plugins/blip/chartdailyfactory.js

Some data may not de displayed after a loading "in place".
Cleanup a little: Remove unused stuff.
Modernize a little the code
Add some documentation

Fix missing daily data after click link param history

---

package-lock.json
package.json
packages/viz/loadtests.js
packages/viz/src/components/trends/common/NoData.js
packages/viz/src/index.js
packages/viz/src/modules/print/index.js
packages/viz/src/utils/annotations.js
packages/viz/src/utils/constants.js
packages/viz/src/utils/stat.js
packages/yourloops/lib/auth/api.ts
packages/yourloops/lib/auth/hook.tsx
packages/yourloops/lib/auth/models.ts
packages/yourloops/lib/language.ts
packages/yourloops/models/locales.ts
packages/yourloops/models/shoreline.ts
packages/yourloops/package.json
packages/yourloops/pages/profile/profile.tsx
packages/yourloops/test/lib/auth/hook.test.tsx

- Rework profile page
- Fix language change & i18next init
- Add missing change password call
- Fix h1bac display
- Fix birthday change
- Fix potential erase seagull current values
- Fix reload page -> uuid version problem

YLP-712 Update password: hcp/caregivers must give current password

---

packages/yourloops/pages/hcp/team-edit-dialog.tsx

* Too big for small screens
* Fix link to terms

Fix modal new team height

---

packages/yourloops/lib/metrics.ts
packages/yourloops/pages/profile/profile.tsx
templates/cookie-banner.js

And fix some metrics where not sent, due to a matomo update sometimes ago

Fix cookie banner localized version id

---

packages/blip/app/components/chart/trends.js
packages/blip/app/components/datepicker/range-datepicker.js
packages/blip/app/components/patient-data.js
packages/blip/test/unit/components/chart/trends.test.js
packages/viz/src/components/trends/common/TrendsContainer.js
packages/viz/test/components/trends/common/TrendsContainer.test.js

* go back/forward/mostRecent add 1 miliseconds more
* Wrong number of displayed days
* Range calendar days selections add 1 more day
* Range calendat min date missing
* Can display before our oldest data

Fix change displayed trends dates

---

packages/yourloops/lib/notifications/api.ts
packages/yourloops/lib/notifications/models.ts
packages/yourloops/pages/hcp/team-members-table.tsx
packages/yourloops/pages/notifications/notification.tsx

Hydrophone >= v1.6.4 is required

Fix allow to cancel invitations

---

templates/stonly.js

Fix deployed on next if you want to verify

Fix loading stonly widget

---

CHANGELOG.md
cloudfront-dist/deployment/package-lock.json
package-lock.json
package.json
server/package-lock.json
server/package.json

- Remove unused dev dep "@types/reach__router"

YLP-808 Regenerate package-lock.json files

---

CHANGELOG.md
packages/yourloops/pages/hcp/team-leave-dialog.tsx
packages/yourloops/pages/hcp/team-member-remove-dialog.tsx

...delete team / remove team member

YLP-831 Missing team name on modals

---

CHANGELOG.md
packages/blip/app/components/chart/trends.js
packages/blip/app/core/api-utils.js
packages/blip/app/core/lib/partial-data-load.js
packages/viz/src/components/trends/common/NoData.js
packages/viz/src/components/trends/common/TrendsContainer.js

... when browsing daily view chronologically (forward)
- Fix trends container: When using the pan buttons there was a shift by one day after loading new data

YLP-820 Data loading loses some days

---

CHANGELOG.md
packages/blip/app/core/api-utils.js
packages/yourloops/lib/data/api.ts
packages/yourloops/lib/data/blip-api.ts
packages/yourloops/lib/data/fetch-summaries.ts
packages/yourloops/models/error.ts

The code was already in place, just add a minor fix, when the is no patient data.

YLP-750 Support TideWhisperer v1 routes

---

CHANGELOG.md
package-lock.json
package.json
packages/blip/test/unit/components/chart/stats.test.js
packages/viz/test/helpers/pdfDoc.js
packages/viz/test/modules/print/BasicsPrintView.test.js
packages/viz/test/modules/print/BgLogPrintView.test.js
packages/viz/test/modules/print/DailyPrintView.test.js
packages/viz/test/modules/print/PrintView.test.js
packages/viz/test/modules/print/SettingsPrintView.test.js
packages/viz/test/modules/print/index.test.js
packages/viz/test/modules/print/utils/constants.test.js
packages/yourloops/lib/cookies-manager.ts
packages/yourloops/lib/zendesk.ts
packages/yourloops/test/lib/cookies-manager.test.ts
packages/yourloops/test/lib/index.ts
packages/yourloops/types/globals.d.ts

- Fix viz tests after sinon bump
- Fix blip test after sinon bump

YLP-813 TU Cookies manager

---

CHANGELOG.md
packages/blip/app/components/chart/daily.js
packages/tideline/js/oneday.js

YLP-852 App crash in the daily view on mobile

---

CHANGELOG.md
packages/blip/app/components/patient-data.js
packages/blip/app/config.js
packages/tideline/js/plot/basal.js
packages/tideline/js/tidelinedata.js
packages/tideline/test/tidelinedata.test.js
packages/yourloops/lib/config.ts
packages/yourloops/models/config.ts
server/config.app.js

YLP-860 Adjust the display of temporay basal

---

CHANGELOG.md
packages/yourloops/components/profile-dialog.tsx
packages/yourloops/pages/hcp/team-members-table.tsx
packages/yourloops/pages/profile/profile.tsx

YLP-910 Fix lastName / firstName / Language translations keys

---

CHANGELOG.md
packages/viz/src/components/settings/CgmTable.js
packages/viz/src/components/settings/Diabeloop.js
packages/viz/src/components/settings/DiabeloopHistoryParameters.js
packages/viz/src/components/settings/PumpTable.js
packages/viz/src/components/settings/TerminalTable.js
packages/viz/src/components/settings/common/Header.js
packages/viz/src/components/settings/common/Table.js
packages/viz/src/utils/settings/diabeloopData.js
packages/yourloops/components/language-select.tsx
packages/yourloops/pages/caregiver/patients/table.tsx
packages/yourloops/pages/hcp/patients/table.tsx
packages/yourloops/pages/signup/signup-account-selector.tsx
packages/yourloops/pages/signup/signup-radio-label.tsx

Can be reviewed, but still in draft for now
We'll see if we needs more

YLP-887 Add more HTML selectors to ease system tests

---

packages/yourloops/components/routes.tsx
packages/yourloops/lib/auth/api.ts
packages/yourloops/lib/auth/hook.tsx
packages/yourloops/pages/caregiver/index.tsx
packages/yourloops/pages/hcp/index.tsx
packages/yourloops/pages/patient/index.tsx

Only after one patient is logged-in after another,
without any other interaction expect logout.

YLP-949 Fix patient is redirected to wrong page after login

---

packages/blip/app/components/chart/basics.js
packages/tideline/plugins/blip/basics/logic/datamunger.js

For some reason this user no longer have "upload" objects in it's data.

YLP-947 Fix App crash on preview

---

CHANGELOG.md
package-lock.json
package.json
packages/blip/package.json
packages/tideline/package.json
packages/viz/package.json
packages/yourloops/package.json

2.0.3 release branch that is used to publish RC

Release 2.0.3

---

CHANGELOG.md
packages/yourloops/components/switch-role/consequences-dialog.tsx
packages/yourloops/pages/signup/signup-stepper.tsx

- change css for aligning text to left
- update changelog

[YLP-958] review text justification in modal windows

---

cloudfront-dist/deploy.sh
cloudfront-dist/deployment/jest.config.js
cloudfront-dist/deployment/lib/staticwebsite-stack.ts
cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json

When a deployment failed, allow to destroy previous configuration
- Bump aws cdk version
- Remove unused packages

CloudFront deploy failed fix

---

packages/yourloops/lib/auth/hook.tsx
packages/yourloops/test/lib/soup/index.ts

Fix validate UUID sometimes not available

---

CHANGELOG.md
packages/yourloops/lib/data/api.ts
packages/yourloops/lib/data/blip-api.ts
packages/yourloops/models/message.ts

New message-api service available as 1.0.0-rc1. See YourLoops updated config here:
https://github.com/mdblp/yourloops/pull/606

YLP-1114 Review routes and data structure for message-api

---

Jenkinsfile
packages/tideline/plugins/nurseshark/index.js
packages/tideline/test/nurseshark.test.js

YLP-1281 Fix data source to diabeloop for all data

---

CHANGELOG.md
README.md
packages/yourloops/README.md
packages/yourloops/test/components/menus/main-drawer.test.tsx
packages/yourloops/test/jest.config.js
packages/yourloops/test/setup.js

Added supports for all the methods found at:
https://github.com/testing-library/jest-dom/#table-of-contents

YLP-1653 Support RTL jest dom for unit tests

---

CHANGELOG.md
packages/viz/src/utils/print/data.js

YLP-1874 Fix PDF report generation

---

CHANGELOG.md
package-lock.json
package.json
packages/yourloops/components/dashboard-widgets/patient-info-widget.tsx
packages/yourloops/pages/profile/profile.tsx

Related PR: https://github.com/mdblp/yourloops/pull/780

YLP-1873 Fix patient profile update not visible in dashboard

---

.github/workflows/ci.yml
.github/workflows/publish_on_request.yml

 Fix publish

---

.github/workflows/publish_on_request.yml

fix publish on comment

---

.github/workflows/ci.yml

Fix CI wrong variable

---

.github/workflows/publish_on_request.yml

Fix admin right

---

CHANGELOG.md
package-lock.json
packages/viz/src/utils/bolus.js
packages/viz/test/utils/bolus.test.js

YLP-1704 pdf generation

---

CHANGELOG.md
packages/dumb/src/components/settings/table.css
packages/dumb/src/components/settings/table.tsx
packages/dumb/src/index.ts
packages/viz/src/components/settings/Diabeloop.js

YLP-2046 Migrate table settings from viz to dumb

---

.github/workflows/publish_on_request.yml

Fix publish pipeline

---

.github/workflows/publish_on_request.yml

Freeze buildkit version in publish action

---

packages/yourloops/pages/login/login-page-desktop.tsx

YLP-1989 new login page

---

packages/blip/app/components/patient-data.js
packages/blip/app/components/patient-data.less

YLP-2004 refine dashboard look and feel

---

packages/dumb/src/components/settings/diabeloop.css
packages/dumb/src/components/settings/history/history-table-header.tsx
packages/dumb/src/components/settings/history/history-table.tsx

This PR is a split of a biggest one #1064  in order to facilitate review, i propose to maintain the checklist on the main one only. what do you think ?

YLP-2088 build header component for historized settings table

---

CHANGELOG.md
cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json
package-lock.json
package.json
packages/blip/package.json
packages/dumb/package.json
packages/medical-domain/package.json
packages/sundial/package.json
packages/tideline/package.json
packages/viz/package.json
packages/yourloops/package.json
server/package-lock.json
server/package.json

YLP-2093 Update blip version to 3.2.0-beta

---

CHANGELOG.md
packages/yourloops/lib/auth/auth.hook.tsx
packages/yourloops/lib/http/axios.service.ts
packages/yourloops/lib/http/http.service.ts

- fix trace token
- update Changelog

YLP-2111 fix trace session change on every request

---

CHANGELOG.md
package-lock.json
packages/dumb/src/components/tooltips/stat-tooltip/stat-tooltip.tsx
packages/yourloops/components/dashboard-widgets/patient-dashboard.tsx
packages/yourloops/components/header-bars/patient-nav-bar-info.tsx
packages/yourloops/components/styled-components.tsx
packages/yourloops/package.json
packages/yourloops/pages/login/login-page-landing.tsx
packages/yourloops/pages/login/verify-email-page.tsx

YLP-2121 Removing deprecated @mui/styles library

---

CHANGELOG.md
packages/yourloops/lib/patient/patient.util.ts
packages/yourloops/test/unit/lib/patient/patient.util.test.ts

YLP-2145 Patient cannot see monitoring widget when he's in a monitoring team and another non-monitoring team

---

.github/workflows/ci.yml
CHANGELOG.md
locales/en/yourloops.json
packages/yourloops/components/menus/drawer/main-drawer.tsx
packages/yourloops/test/integration/assert/drawer.ts
packages/yourloops/test/unit/components/menus/main-drawer.test.tsx

YLP-2220 Remove "private practice" filter from patients list

---

CHANGELOG.md
package-lock.json
packages/yourloops/app/app.tsx
packages/yourloops/lib/auth/auth.hook.tsx
packages/yourloops/package.json
packages/yourloops/pages/login/login-page-desktop.tsx
packages/yourloops/pages/login/login-page-mobile.tsx
packages/yourloops/pages/login/verify-email-page.tsx
packages/yourloops/test/integration/pages/login/login-page-desktop.spec.tsx
packages/yourloops/test/integration/pages/login/login-page-mobile.spec.tsx
packages/yourloops/test/integration/pages/patient-dashboard/patient-dashboard-common.spec.tsx
packages/yourloops/test/integration/pages/profile/caregiver-profile.spec.tsx
packages/yourloops/test/integration/pages/signup-stepper/caregiver-signup.spec.tsx
packages/yourloops/test/integration/pages/signup-stepper/hcp-signup.spec.tsx
packages/yourloops/test/unit/lib/auth/auth.hook.test.tsx

YLP-2252 Bump auth0-react from 1.9.0 to 2.0.1

---

CHANGELOG.md
locales/en/yourloops.json
packages/yourloops/components/header-bars/main-header.tsx
packages/yourloops/components/menus/drawer/main-drawer.tsx
packages/yourloops/components/patient-list/patient-list-header.tsx
packages/yourloops/components/patient-list/patient-list.hook.tsx
packages/yourloops/components/patient-list/patient-list.tsx
packages/yourloops/lib/patient/models/patient-context-result.model.ts
packages/yourloops/lib/patient/models/patient-filter-stats.model.ts
packages/yourloops/lib/patient/models/patient.model.ts
packages/yourloops/lib/patient/patient.hook.tsx
packages/yourloops/lib/patient/patient.util.ts
packages/yourloops/test/integration/assert/drawer.ts
packages/yourloops/test/integration/assert/patient-list-header.ts
packages/yourloops/test/integration/pages/home-page/caregiver-home-page.spec.tsx
packages/yourloops/test/integration/pages/home-page/hcp-home-page.spec.tsx
packages/yourloops/test/unit/components/menus/main-drawer.test.tsx
packages/yourloops/test/unit/lib/patient/patient.util.test.ts

YLP-2146 Patient list groups (current and pending)

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
test/locales/locales-files.test.js

Rename master branch from 'dblp' to 'main'

---

CHANGELOG.md
packages/yourloops/lib/patient/models/patient.model.ts
packages/yourloops/lib/patient/patient.api.ts
packages/yourloops/lib/patient/patient.util.ts
packages/yourloops/test/integration/data/patient.api.data.ts
packages/yourloops/test/integration/mock/patient-login.mock.ts
packages/yourloops/test/integration/mock/patient.api.mock.ts
packages/yourloops/test/integration/pages/daily/daily-view.common.spec.tsx
packages/yourloops/test/integration/pages/daily/daily-view.patient.spec.tsx
packages/yourloops/test/integration/pages/trends/trends-view.common.spec.tsx
packages/yourloops/test/integration/pages/trends/trends-view.patient.spec.tsx
packages/yourloops/test/unit/lib/patient/patient.api.test.ts

YLP-2418 use new patient route from harbour 

---

CHANGELOG.md
packages/blip/app/components/chart/daily.js

YLP-2454 daily crashes mobile

---

.github/dependabot.yml
CHANGELOG.md

YLP-2458 Blip auto dependencies update

---

CHANGELOG.md
packages/yourloops/components/patient-list/current-patient-list/current-patient-list.hook.tsx
packages/yourloops/components/patient/utils.ts
packages/yourloops/lib/team/models/i-team-member.model.ts
packages/yourloops/test/integration/data/patient-builder.data.ts
packages/yourloops/test/integration/pages/home/home.caregiver.spec.tsx
packages/yourloops/test/unit/pages/hcp/patients/patient-utils.test.tsx

YLP-2460 Caregiver users cannot see the "Last data update" date in the patients list

---

CHANGELOG.md
cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json
package-lock.json
package.json
packages/blip/package.json
packages/dumb/package.json
packages/medical-domain/package.json
packages/sundial/package.json
packages/tideline/package.json
packages/viz/package.json
packages/yourloops/package.json
server/package-lock.json
server/package.json

Init 3.0.5 version

---

CHANGELOG.md
packages/yourloops/components/chat/chat-widget.tsx

YLP-2498 Fix chat widget minimal height

---

CHANGELOG.md
packages/yourloops/components/footer/footer.tsx

YLP-2495 Fix spacing between links in app footer

---

CHANGELOG.md
packages/yourloops/components/footer/footer.tsx

Empty 3.0.5 version

---

CHANGELOG.md
packages/yourloops/components/device/parameters-change-history.tsx
packages/yourloops/components/device/utils/device.utils.ts

YLP-2502 history unsorted

---

CHANGELOG.md
packages/dumb/src/index.ts
packages/yourloops/components/device/device-settings.tsx
packages/yourloops/components/device/parameters-change-history.tsx
packages/yourloops/lib/utils.ts

YLP-2503 Device settings history is not taking timezone into account

---

CHANGELOG.md
cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json
package-lock.json
package.json
packages/blip/package.json
packages/dumb/package.json
packages/medical-domain/package.json
packages/sundial/package.json
packages/tideline/package.json
packages/viz/package.json
packages/yourloops/package.json
server/package-lock.json
server/package.json

Init version 3.0.4-rc3

---

CHANGELOG.md
packages/tideline/js/plot/warmup.js

YLP-2509 sensor warmup not showing

---

CHANGELOG.md
packages/yourloops/components/patient-data/patient-data.utils.ts

YLP-2510 Static dashboard does not perform calculation based on the last 14 days

---

CHANGELOG.md
packages/yourloops/components/patient-data/patient-data.hook.ts

YLP-2519 Fix refresh on Daily view disabling the forward arrow in the date picker

---

CHANGELOG.md
packages/medical-domain/src/domains/repositories/statistics/insulin-statistics.service.ts
packages/yourloops/components/patient-data/patient-data.hook.ts

YLP-2511 In the daily view, not all graph data is taken into account by the loop mode

---

CHANGELOG.md
cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json
package-lock.json
package.json
packages/blip/package.json
packages/dumb/package.json
packages/medical-domain/package.json
packages/sundial/package.json
packages/tideline/package.json
packages/viz/package.json
packages/yourloops/package.json
server/package-lock.json
server/package.json

Init version 3.0.4-rc4

---

CHANGELOG.md
packages/medical-domain/src/domains/models/medical/datum/wizard.model.ts
packages/medical-domain/src/domains/repositories/medical/datum/wizard.service.ts
packages/medical-domain/src/domains/repositories/medical/medical-data.service.ts
packages/medical-domain/test/data-generator.ts
packages/medical-domain/test/repositories/medical/datum/wizard.service.test.ts
packages/medical-domain/test/repositories/medical/medical-data.service.test.ts

YLP-2525 The carbs information is duplicated

---

CHANGELOG.md
packages/yourloops/components/device/parameter-change-value.tsx

YLP-2539 Update arrow icon in Device parameters change history

---

CHANGELOG.md
packages/yourloops/components/menus/team-scope-menu.tsx
packages/yourloops/components/monitoring-alert/monitoring-alerts-card.tsx
packages/yourloops/components/team/team-information.tsx
packages/yourloops/components/team/team-members.tsx
packages/yourloops/components/team/team-monitoring-alerts-configuration.tsx

YLP-2514 Add Stonly ids to display 3.0.4 updates via triggers

---

CHANGELOG.md
packages/dumb/src/components/stats/cbg-mean/cbg-mean-stat.css
packages/dumb/src/components/stats/cbg-mean/cbg-mean-stat.tsx
packages/dumb/src/components/stats/cbg-percentage/cbg-percentage-bar-chart.tsx
packages/dumb/src/components/stats/cbg-percentage/cbg-percentage-bar.css
packages/dumb/src/components/stats/cbg-standard-deviation/cbg-standard-deviation.css
packages/dumb/src/components/stats/cbg-standard-deviation/cbg-standard-deviation.tsx
packages/dumb/src/components/stats/common/cbg-common.css
packages/dumb/src/components/stats/insulin/insulin-stat.css
packages/dumb/src/styles/typography.css

YLP-2536 Gain some space in statistics

---

packages/tideline/css/tideline.less

YLP-2524 Override information is hardly visible

---

CHANGELOG.md
cloudfront-dist/deployment/README.md
cloudfront-dist/deployment/lib/lambda-stack.ts
cloudfront-dist/deployment/lib/staticwebsite-stack.ts
cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json

- [!] Code tested (unit tests and integration tests)
- [!] Copyright added on every file
- [!] End-to-end tests successful on CI

YLP-2571 Upgrade SSL security policy for cloudfront distributions

---

packages/yourloops/.eslintrc.json

adding rules to reactivate linter

---

packages/yourloops/pages/patient/caregivers/secondary-bar.tsx

[TEST - Do not merge] Test commit

---

packages/yourloops/pages/patient/caregivers/secondary-bar.tsx

[TEST - Do not review] Test commit (#1441)

---

CHANGELOG.md
packages/yourloops/app/error.tsx
packages/yourloops/test/integration/pages/error/error.common.spec.tsx

YLP-2631 Calls made to /harbour/errors do not always give an error message

---

CHANGELOG.md
packages/yourloops/components/dialogs/join-team/privacy-policy-confirm.tsx
templates/index.html

YLP-2642 Disabled Google Translate automated translation to avoid React crashes

---

packages/yourloops/test/tsconfig.test.json

Fixed autocomplete in tests

---

.eslintrc.json
package-lock.json
package.json
packages/dumb/.eslintrc.json
packages/dumb/src/modules/print/print-view/print-view.util.test.ts
packages/medical-domain/.eslintrc.json
packages/medical-domain/test/repositories/time/time.service.test.ts
packages/yourloops/.eslintrc.json
packages/yourloops/test/integration/assert/medical-widget.assert.ts
packages/yourloops/test/integration/jest.config.js
packages/yourloops/test/integration/pages/error/error.common.spec.tsx
packages/yourloops/test/integration/pages/home/home.caregiver.spec.tsx
packages/yourloops/test/unit/components/date-pickers/dialog-range-date-picker.test.tsx
packages/yourloops/test/unit/components/dialogs/leave-team-dialog.test.tsx
packages/yourloops/test/unit/components/monitoring-alert/monitoring-alert-content-configuration.util.test.ts
packages/yourloops/test/unit/components/monitoring-alert/monitoring-alerts-content-configuration.hook.test.tsx
packages/yourloops/test/unit/lib/auth/auth.api.test.ts
packages/yourloops/test/unit/lib/auth/user.api.test.ts
packages/yourloops/test/unit/lib/data/data.api.test.ts
packages/yourloops/test/unit/lib/http/http.service.test.ts
packages/yourloops/test/unit/lib/metrics.test.tsx
packages/yourloops/test/unit/lib/patient/patient.api.test.ts
packages/yourloops/test/unit/lib/patient/patient.hook.test.tsx
packages/yourloops/test/unit/lib/patient/patients.hook.test.tsx
packages/yourloops/test/unit/lib/regex.test.tsx
packages/yourloops/test/unit/lib/team/team.api.test.ts
packages/yourloops/test/unit/lib/team/team.hook.test.tsx

Added eslint-plugin-jest

---

CHANGELOG.md
packages/dumb/src/modules/print/settings-print-view/settings-print-view.util.ts
packages/medical-domain/src/domains/models/medical/datum/pump-settings.model.ts
packages/medical-domain/src/domains/repositories/medical/datum/pump-settings.service.ts
packages/medical-domain/src/domains/repositories/medical/medical-data.service.ts
packages/tideline/js/plot/reservoir.js
packages/tideline/plugins/blip/basics/components/chart/SiteChange.js
packages/tideline/plugins/blip/basics/components/sitechange/Change.js
packages/tideline/plugins/blip/basics/logic/constants.js
packages/tideline/plugins/blip/basics/logic/state.js
packages/yourloops/components/device/pump-info-table.tsx

YLP-2661 App crashes when patient does not have a pump

---

CHANGELOG.md
packages/yourloops/app/error.tsx
packages/yourloops/test/integration/pages/error/error.common.spec.tsx

YLP-2672 Error code given by the front should be findable in kibana

---

CHANGELOG.md
packages/yourloops/components/chat/chat-widget.tsx
packages/yourloops/components/dashboard-widgets/device-usage-widget.tsx
packages/yourloops/components/dashboard-widgets/generic-dashboard-card.tsx
packages/yourloops/components/dashboard-widgets/medical-files/medical-files-widget.tsx
packages/yourloops/components/dashboard-widgets/patient-statistics-widget.tsx
packages/yourloops/components/header-bars/patient-nav-bar-tabs.tsx
packages/yourloops/components/monitoring-alert/monitoring-alerts-card.tsx

YLP-2668 Remove icons of the tabs and widget titles

---

CHANGELOG.md
locales/en/yourloops.json
packages/medical-domain/test/utils/typeguard.utils.test.ts
packages/yourloops/app/error.tsx
packages/yourloops/lib/browser.ts
packages/yourloops/lib/language.ts
packages/yourloops/test/integration/assert/patient-list.assert.ts
packages/yourloops/test/integration/pages/error/error.common.spec.tsx
packages/yourloops/test/unit/lib/browser.test.ts

YLP-2652 Improve error message on app crash

---

CHANGELOG.md
packages/yourloops/components/header-bars/patient-nav-bar-tabs.tsx
packages/yourloops/components/patient-data/patient-data.tsx
packages/yourloops/test/integration/assert/patient-list.assert.ts
packages/yourloops/test/integration/assert/patient-nav-bar.assert.ts
packages/yourloops/test/integration/pages/patient-view/daily/daily-view.hcp.spec.tsx
packages/yourloops/test/integration/pages/patient-view/dashboard/dashboard-view.hcp.spec.tsx
packages/yourloops/test/integration/pages/patient-view/trends/trends-view.hcp.spec.tsx
packages/yourloops/test/integration/use-cases/app-main-layout-visualisation.ts
packages/yourloops/test/integration/use-cases/patient-data-visualisation.ts

YLP-2670 Remove target & alerts view from "private practice"

---

CHANGELOG.md
cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json
package-lock.json
package.json
packages/blip/package.json
packages/dumb/package.json
packages/medical-domain/package.json
packages/tideline/package.json
packages/viz/package.json
packages/yourloops/package.json
server/package-lock.json
server/package.json

Init version 3.0.5-rc1

---

CHANGELOG.md
cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json
package-lock.json
package.json
packages/blip/package.json
packages/dumb/package.json
packages/medical-domain/package.json
packages/tideline/package.json
packages/viz/package.json
packages/yourloops/package.json
server/package-lock.json
server/package.json

Init version 3.0.5-rc2

---

cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json
package-lock.json
package.json
packages/blip/package.json
packages/dumb/package.json
packages/medical-domain/package.json
packages/tideline/package.json
packages/viz/package.json
packages/yourloops/package.json
server/package-lock.json
server/package.json

Init version 3.0.6

---

Dockerfile
cloudfront-dist/deployment/README.md
cloudfront-dist/deployment/bin/staticwebsite-cdk.ts
cloudfront-dist/deployment/cdk.json
cloudfront-dist/deployment/lib/lambda-stack.ts
cloudfront-dist/deployment/lib/props/WebStackProps.ts
cloudfront-dist/deployment/lib/staticwebsite-stack.ts
cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json

YLP-1954 update aws cdk version

---

CHANGELOG.md
packages/medical-domain/src/domains/models/medical/datum/enums/unit.enum.ts
packages/yourloops/components/device/utils/device.utils.ts

YLP-2586 Display height in device parameters

---

CHANGELOG.md
cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json
package-lock.json
package.json
packages/blip/package.json
packages/dumb/package.json
packages/medical-domain/package.json
packages/tideline/package.json
packages/viz/package.json
packages/yourloops/package.json
server/package-lock.json
server/package.json

Init version 3.3.0-beta

---

CHANGELOG.md
packages/yourloops/components/patient-data/patient-data.tsx
packages/yourloops/components/patient-data/patient-data.utils.ts

Merge v3.2.0 in main

---

CHANGELOG.md
packages/blip/app/components/messages/messageform.js

YLP-2951 Prevent creation of a message (note) with an empty timestamp

---

CHANGELOG.md
cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json
package-lock.json
package.json
packages/blip/package.json
packages/dumb/package.json
packages/medical-domain/package.json
packages/tideline/package.json
packages/viz/package.json
packages/yourloops/package.json
server/package-lock.json
server/package.json

Init version 3.3.0-rc1

---

CHANGELOG.md
cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json
package-lock.json
package.json
packages/blip/package.json
packages/dumb/package.json
packages/medical-domain/package.json
packages/tideline/package.json
packages/viz/package.json
packages/yourloops/package.json
server/package-lock.json
server/package.json

Freeze version 3.3.0

---

CHANGELOG.md
cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json
package-lock.json
package.json
packages/blip/package.json
packages/dumb/package.json
packages/medical-domain/package.json
packages/tideline/package.json
packages/viz/package.json
packages/yourloops/package.json
packages/yourloops/test/integration/assert/device-usage.assert.ts
server/package-lock.json
server/package.json

YLP-2948 Updated failing tests because of the time change

---

CHANGELOG.md
packages/dumb/src/components/tooltips/common/tooltip/tooltip.tsx
packages/dumb/src/components/tooltips/parameter-tooltip/parameter-tooltip.tsx
packages/tideline/js/plot/alarmEvent.js
packages/tideline/js/plot/deviceParameterChange.js
packages/tideline/js/plot/reservoir.js
packages/tideline/js/plot/util/drawphysicalactivity.js
packages/tideline/js/plot/util/eventsConstants.js
packages/tideline/js/plot/warmup.js
packages/tideline/js/plot/zenModeEvent.js
packages/tideline/js/pool.js
packages/tideline/plugins/blip/chartdailyfactory.js
packages/yourloops/components/date-pickers/daily-date-picker.tsx

YLP-2866 Display events in a dedicated section in Daily view

---

CHANGELOG.md
branding/palette.css
packages/dumb/src/components/stats/cbg-mean/cbg-mean-stat.tsx
packages/dumb/src/components/stats/cbg-percentage/cbg-percentage-bar.css
packages/dumb/src/components/stats/cbg-percentage/cbg-percentage-bar.hook.tsx
packages/dumb/src/components/stats/cbg-percentage/cbg-percentage-title.tsx
packages/dumb/src/components/stats/cbg-standard-deviation/cbg-standard-deviation.css
packages/dumb/src/components/stats/cbg-standard-deviation/cbg-standard-deviation.tsx
packages/dumb/src/components/stats/common/cbg-colors.css
packages/dumb/src/components/stats/common/simple-value.css
packages/dumb/src/components/stats/insulin/insulin-stat.css
packages/dumb/src/components/stats/insulin/insulin-stat.tsx
packages/dumb/src/components/stats/loop-mode-stat/loop-mode-stat.css
packages/dumb/src/components/stats/loop-mode-stat/loop-mode-stat.tsx
packages/dumb/src/components/stats/simple/simple-stat.css
packages/dumb/src/components/stats/simple/simple-stat.util.ts
packages/dumb/src/components/stats/stat-legend/stat-legend.css
packages/dumb/src/components/stats/total-carbs/total-carbs-stat.css
packages/dumb/src/components/stats/total-carbs/total-carbs-stat.tsx
packages/dumb/src/styles/stat-common.css
packages/tideline/plugins/blip/basics/components/DashboardSection.js
packages/tideline/plugins/blip/basics/less/DashboardSection.less
packages/tideline/plugins/blip/chartdailyfactory.js
packages/yourloops/components/dashboard-widgets/device-usage-widget.tsx
packages/yourloops/components/statistics/carbs-stat.tsx

YLP-3019 New design for stats

---

CHANGELOG.md
locales/en/yourloops.json
locales/languages.json
packages/yourloops/lib/auth/models/country.model.ts
packages/yourloops/test/integration/pages/profile/profile.hcp.spec.tsx
packages/yourloops/test/integration/pages/signup-stepper/signup.caregiver.spec.tsx
packages/yourloops/test/integration/pages/signup-stepper/signup.hcp.spec.tsx
test/locales/translations.test.js

YLP-3075 As a user, I want to be able to choose Japan or UK country

---

CHANGELOG.md
packages/tideline/js/plot/quickbolus.js
packages/tideline/js/plot/util/fill.js
packages/tideline/plugins/blip/chartdailyfactory.js

YLP-2527 meal carbs hidden behind a bolus bar

---

artifact-lang.sh

Fix parameters translation script

---

CHANGELOG.md
packages/tideline/js/plot/confidentialModeEvent.js
packages/tideline/plugins/blip/chartdailyfactory.js

YLP-3172 Hide Confidential Mode label on Events graph

---

CHANGELOG.md
packages/dumb/src/styles/colors.css
packages/viz/src/styles/colors.css

YLP-3165 Update basal color

---

CHANGELOG.md
cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json
package-lock.json
package.json
packages/blip/package.json
packages/dumb/package.json
packages/medical-domain/package.json
packages/tideline/package.json
packages/viz/package.json
packages/yourloops/package.json
server/package-lock.json
server/package.json

bump version 3.4.0-rc1

---

CHANGELOG.md
cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json
package-lock.json
package.json
packages/blip/package.json
packages/dumb/package.json
packages/medical-domain/package.json
packages/tideline/package.json
packages/viz/package.json
packages/yourloops/package.json
server/package-lock.json
server/package.json

Blip 3.5.0-beta

---

CHANGELOG.md
packages/yourloops/components/patient/utils.ts
packages/yourloops/lib/auth/models/settings.model.ts
packages/yourloops/lib/utils.ts
packages/yourloops/test/integration/assert/patient-list.assert.ts
packages/yourloops/test/integration/data/patient.api.data.ts
packages/yourloops/test/unit/pages/hcp/patients/patient-utils.test.tsx

YLP-3128 As an HCP, I want to see which device is used by each patient

---

CHANGELOG.md
packages/medical-domain/src/domains/repositories/medical/datum.service.ts
packages/medical-domain/src/domains/repositories/statistics/insulin-statistics.service.ts
packages/medical-domain/test/mock/data.statistics.mock.ts
packages/medical-domain/test/repositories/statistics/insulin-statistics.service.test.ts
packages/yourloops/test/integration/assert/patient-statistics.assert.ts
packages/yourloops/test/integration/use-cases/patient-data-visualisation.ts

YLP-3255 Fix insulin stat computation for basal & correction bolus

---

CHANGELOG.md
cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json
package-lock.json
package.json
packages/blip/package.json
packages/dumb/package.json
packages/medical-domain/package.json
packages/tideline/package.json
packages/viz/package.json
packages/yourloops/package.json
server/package-lock.json
server/package.json

Bump version to 3.4.2-rc1

---

CHANGELOG.md
packages/tideline/plugins/blip/chartdailyfactory.js

(cherry picked from commit 6bf51a366b777de9e061e5f88ab375053152337b)

YLP-3310 Display Physical Activity below other events in Daily view (#1750)

---

CHANGELOG.md
cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json
package-lock.json
package.json
packages/blip/package.json
packages/dumb/package.json
packages/medical-domain/package.json
packages/tideline/package.json
packages/viz/package.json
packages/yourloops/package.json
server/cloudfront-gen-lambda.js
server/package-lock.json
server/package.json

Fix CSP for product labels

---

CHANGELOG.md
packages/viz/src/modules/print/DailyPrintView.js

YLP-2543 Fix PDF basal legend color

---

CHANGELOG.md
packages/yourloops/test/integration/assert/patient-list.assert.ts
packages/yourloops/webpack.config.js
server/cloudfront-gen-lambda.js
templates/lambda-request-viewer.js
test/lambda/cloudfront-gen-lambda.test.js

YLP-3242 Add md5 to palette and config file

---

CHANGELOG.md
packages/medical-domain/src/domains/models/medical/datum/wizard.model.ts
packages/medical-domain/src/domains/repositories/medical/datum/wizard.service.ts
packages/medical-domain/src/domains/repositories/medical/medical-data.service.ts
packages/medical-domain/src/domains/repositories/statistics/insulin-statistics.service.ts
packages/medical-domain/test/mock/data.statistics.mock.ts
packages/medical-domain/test/repositories/medical/medical-data.service.test.ts
packages/medical-domain/test/repositories/statistics/insulin-statistics.service.test.ts

fix bolus total with biphasic counted

---

CHANGELOG.md
packages/yourloops/components/patient-data/patient-data.tsx
packages/yourloops/components/pdf/print-pdf-dialog.tsx
packages/yourloops/components/pdf/print-report-dialog.tsx
packages/yourloops/lib/data/data.api.ts
packages/yourloops/lib/data/models/csv-report.model.ts
packages/yourloops/lib/http/models/enums/http-header-keys.enum.ts
packages/yourloops/lib/http/models/enums/http-header-values.enum.ts
packages/yourloops/test/integration/assert/report-dialog.assert.ts
packages/yourloops/test/integration/pages/patient-view/daily/daily-view.common.spec.tsx
packages/yourloops/test/unit/lib/data/data.api.test.ts

- **plug new report endpoint**
- **remove console log**
- **fix: alerts raised react error when passing an error instead of an string**
- **refacto: rename component to report dialog**

YLP-3145 as a ylp user i want to do a csv report

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/publish_on_request.yml
README.md
docs/howto-manualy-run-a-workflow.md

- **migrate codeql-analysis.yml**
- **migrate publish_on_request.yml**
- **migrate ci**

bump github actions new version

---

CHANGELOG.md
packages/dumb/src/index.ts
packages/dumb/src/models/print/pdf-settings-table.model.ts
packages/dumb/src/models/safety-basal-item.model.ts
packages/dumb/src/modules/print/settings-print-view/settings-print-view.ts
packages/dumb/src/modules/print/settings-print-view/settings-print-view.util.ts
packages/dumb/src/utils/safety-basal-profile/safety-basal-profile.util.test.ts
packages/dumb/src/utils/safety-basal-profile/safety-basal-profile.util.ts
packages/yourloops/pages/patient-view/devices/sections/safety-basal-profile-section.tsx
test/locales/translations.test.js

YLP-2692 Display basal safety profile in the PDF report

---

CHANGELOG.md
cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json
package-lock.json
package.json
packages/blip/package.json
packages/dumb/package.json
packages/medical-domain/package.json
packages/tideline/package.json
packages/viz/package.json
packages/yourloops/package.json
server/package-lock.json
server/package.json

Bump version 3.6.0-rc1

---

CHANGELOG.md
cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json
package-lock.json
package.json
packages/blip/package.json
packages/dumb/package.json
packages/medical-domain/package.json
packages/tideline/package.json
packages/viz/package.json
packages/yourloops/package.json
server/package-lock.json
server/package.json

Bump version 3.6.0

---

CHANGELOG.md
cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json
package-lock.json
package.json
packages/blip/package.json
packages/dumb/package.json
packages/dumb/src/index.ts
packages/dumb/src/modules/print/settings-print-view/settings-print-view.ts
packages/dumb/src/utils/safety-basal-profile/safety-basal-profile.util.test.ts
packages/dumb/src/utils/safety-basal-profile/safety-basal-profile.util.ts
packages/medical-domain/package.json
packages/tideline/package.json
packages/viz/package.json
packages/yourloops/package.json
packages/yourloops/pages/patient-view/devices/sections/safety-basal-profile-section.tsx
server/package-lock.json
server/package.json

Fix safety basal bug + bump version to 3.6.0-rc2

---

CHANGELOG.md
cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json
package-lock.json
package.json
packages/blip/package.json
packages/dumb/package.json
packages/dumb/src/index.ts
packages/dumb/src/modules/print/settings-print-view/settings-print-view.ts
packages/dumb/src/utils/safety-basal-profile/safety-basal-profile.util.test.ts
packages/dumb/src/utils/safety-basal-profile/safety-basal-profile.util.ts
packages/medical-domain/package.json
packages/tideline/package.json
packages/viz/package.json
packages/yourloops/package.json
packages/yourloops/pages/patient-view/devices/sections/safety-basal-profile-section.tsx
server/package-lock.json
server/package.json

Merge v3.6.0 in main + bump to v3.7.0-beta

---

CHANGELOG.md
packages/blip/app/core/less/variables.less

YLP-3290 Top banner is hiding the top part of note creation popup

---

CHANGELOG.md
cloudfront-dist/assets/maintenance/index.html

YLP-3478 update status page

---

CHANGELOG.md
cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json
package-lock.json
package.json
packages/blip/package.json
packages/dumb/package.json
packages/medical-domain/package.json
packages/tideline/package.json
packages/viz/package.json
packages/yourloops/package.json
server/package-lock.json
server/package.json

Bump blip to 3.7.0-rc1

---

CHANGELOG.md
cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json
package-lock.json
package.json
packages/blip/package.json
packages/dumb/package.json
packages/dumb/src/components/tooltips/night-mode-tooltip/night-mode-tooltip.tsx
packages/dumb/src/utils/datetime/datetime.util.ts
packages/medical-domain/package.json
packages/tideline/package.json
packages/viz/package.json
packages/yourloops/package.json
server/package-lock.json
server/package.json

YLP-3653 Handle night mode events lasting less than 1 hour

---

cloudfront-dist/deployment/package-lock.json
cloudfront-dist/deployment/package.json
package-lock.json
package.json
packages/blip/package.json
packages/dumb/package.json
packages/medical-domain/package.json
packages/tideline/package.json
packages/viz/package.json
packages/yourloops/package.json
server/package-lock.json
server/package.json

Bump version to 3.8.0-beta

---

CHANGELOG.md
packages/tideline/plugins/blip/chartdailyfactory.js

---
:camera: UI screenshot (if applicable):

YLP-3710 feat: Move the "EVENTS" section above the glycemia curve
